### ISSUE TITLE
[BUG] With multi-window mode, some apps or render surfaces appear translucent

### ISSUE THREAD

**Issue by kode54** [waydroid/waydroid#1352]
### Describe the bug

In multi-window mode, I realize it appears that Waydroid is rendering a transparent full desktop window layer, with the windows as sub-surfaces of this window, including the cursor. The problem is, some apps, such as 3DMark's Vulkan benchmarks, render with the display surface area as alpha 0, and the color channels appearing to be treated as pre-multiplied by alpha, so their color values are added to the pixels underneath of the Waydroid window.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Arch Linux

### Kernel version

6.8.4-1-cachyos

### Desktop Environment

labwc-git 0.7.1.r90.g5cc07573-1

### GPU

AMD Radeon RX 6700 XT

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
[waydroid_stuff.3.tar.gz](https://github.com/waydroid/waydroid/files/14880415/waydroid_stuff.3.tar.gz)

`sudo waydroid shell -- logcat -d | tee logcat.txt`
[logcat.3.txt](https://github.com/waydroid/waydroid/files/14880420/logcat.3.txt)

`sudo dmesg | tee dmesg.txt`
[dmesg.3.txt](https://github.com/waydroid/waydroid/files/14880421/dmesg.3.txt)

And a video of the thing happening:
![3dmark_translucent.mp4](https://f.losno.co/v/3dmark_translucent.mp4)

**Comment by aleasto** [comment]
So I guess we need a black background?

**Comment by kode54** [comment]
Or I could just run certain apps in full-ui mode. It's probably the app misbehaving.

**Comment by OlegAckbar** [comment]
I can confirm this issue. In some games effects are translucent, for example in Subway Surfers sky is completely translucent. [Screen Recording_20240525_015037_2.webm](https://github.com/waydroid/waydroid/assets/9915567/c9304cd5-7dcc-4f6c-b13b-492aafb839eb)

**Comment by WesleyVanNeck** [comment]
> So I guess we need a black background? Like we already do for full-ui mode.

Yes

**Comment by ging-dev** [comment]
same problem!

**Comment by ShaunTheSalvo** [comment]
As a workaround, I open a terminal window (I use xterm for the purpose) with a black window background and black text (`xterm -bg black -fullscreen`), then run my Waydroid app: per example

`xterm -bg black -fullscreen & waydroid app launch com.app.name`

Xterm creates a fully black background with no titlebar etc, and then the Waydroid app runs over the top of it. By default, Xterm's terminal text is also black, so no text should show up.

You can add the `xterm -bg black -fullscreen &` to the start of the exec line in the .desktop files for any Waydroid apps you need a black background for. You can find the .desktop files of your Waydroid apps in `$HOME/.local/share/applications`.

The only minor niggle is that the Xterm window will still be open after the Waydroid app is exited (eg when you finish playing your game). As a workaround to _that_, the following command will (1) run Xterm as a full-screen black window, (2) run the Waydroid app, (3) wait for the Waydroid app to terminate, and then (4) close the Xterm window.

`xterm -bg black -fullscreen & waydroid app launch com.foo.bar ; while pgrep com.foo.bar > /dev/null; do sleep 1; done ; killall -9 xterm`

The pgrep command has a limit of 15 characters to search for a process name, which will be the Android app name. Fotunately we can use just part of the app name for the pgrep command. For example, instead of `pgrep com.app.with.very.long.name`, you could just use `pgrep long.name`; the Android app's name should be unique enough for this to work. 

It's a bit of a fiddly workaround, and definitely a bit hacky, but it does work well. I'm running Waydroid on Arch Linux with KDE desktop. Note the Waydroid app will still be transparent, it just has a black background behind it. You could always experiment with different colours for the Xterm window (white, grey etc.) to see if you get better results; it may depend on the Android app in question as to which is best. Obviously, you'll need xterm installed on your system for it to work (duh).

Hope this helps someone.

**Comment by Rail27** [comment]
> Yeah, it may not work on everything, unfortunately. As I said, it's a workaround, rather than a fix. I'll try that APK later today, and see what happens on my machine. I'll report back here.

Really thank you!! I love this game! If I can play this, I'll very happy. So I want to do everything I can.
I'm very and really happy to there are people out there who are serious about this thing!

I'll do my best too! If I find out anything knowledges about this, I'll let report to here!

**Comment by ShaunTheSalvo** [comment]
Unfortunately I have no idea on how else to work around the problem. Nvidia doesn't have great support in Linux across the board unfortunately, which is a shame as they're pretty powerful GPUs. I hope you can find a solution; unfortunately I'm out of ideas.

**Comment by sebderiv** [comment]
Hello, any update on this issue ? I have the same behavior on games like Epic Seven (they have a lot of transparency effects when you open some menus). I don't like playing Android games in full screen on my computer so always having to manage 2 windows (the terminal "background" + the game) each time I'm switching from the game to other stuff and vice-versa is quite annoying.

**Comment by ghost** [comment]
> Hello, any update on this issue ? I have the same behavior on games like Epic Seven (they have a lot of transparency effects when you open some menus). I don't like playing Android games in full screen on my computer so always having to manage 2 windows (the terminal "background" + the game) each time I'm switching from the game to other stuff and vice-versa is quite annoying.

What I actually did was launch in full-screen mode and force a specific resolution to achieve the desired size. By then using the window movement functionality of the host OS, it becomes completely possible to avoid the bug without any issues.
However, please note that the bug itself related to the NVIDIA GPU, which I was experiencing, is not resolved by this method.

**Comment by ShaunTheSalvo** [comment]
> What I actually did was launch in full-screen mode and force a specific resolution to achieve the desired size. By then using the window movement functionality of the host OS, it becomes completely possible to avoid the bug without any issues. However, please note that the bug itself related to the NVIDIA GPU, which I was experiencing, is not resolved by this method.

I'm not aware of any other solution at this stage. Disabling multi-window mode and using full-screen mode resolves the transparency issue, obviously at the expense of multi-window functionality. As I use Waydroid for other apps besides games, I prefer the multi-window option. Hopefully a more practical solution might eventuate in the future. Perhaps if it became possible to use the host OS's window manager (instead of Android's multi-window option) might be helpful. I don't know of any way of doing that though.

**Comment by G-Titan** [comment]
Dec 22-2025 Problem still persists. I will join the team next yer to help resolve it because I want to play PUBG & CODM on my i3 7th Gen CPU

Am I asking for too much if back in the day when any windows version could run android emulators and just play mobile games without a fuss?
Proton is doing something including heroic but Google play &/ the Android ecosystem?

**Comment by WesleyVanNeck** [comment]
Any news on this
