### ISSUE TITLE
[BUG] lxc_end: 986 Failed to run lxc.hook.post-stop for container "waydroid"

### ISSUE THREAD

**Issue by psammarco** [waydroid/waydroid#1423]
### Describe the bug

Basically /dev/binder dies soon after running _waydroid session start_ .

```
pietro@toilet ~ $ waydroid session start
[gbinder] Service manager /dev/binder has appeared
[gbinder] WARNING: Service manager /dev/binder has died
```
**Output of waydroid log**
```
(002447) [11:11:49] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(002447) [11:11:49] % systemctl is-active -q nfcd
(002447) [11:11:49] % chmod 777 -R /dev/dri
(002447) [11:11:49] % chmod 777 -R /dev/fb0
(002447) [11:11:49] % chmod 777 -R /dev/video0
(002447) [11:11:49] % chmod 777 -R /dev/video1
(002447) [11:11:49] % chmod 777 -R /dev/video2
(002447) [11:11:49] % chmod 777 -R /dev/video3
(002447) [11:11:49] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(002447) [11:11:49] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(002447) [11:11:49] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(002447) [11:11:49] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(002447) [11:11:49] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(002447) [11:11:49] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(002447) [11:11:49] Save config: /var/lib/waydroid/waydroid.cfg
(002447) [11:11:49] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(002447) [11:11:49] New background process: pid=9135, output=background
(002447) [11:11:49] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
RUNNING
lxc-start: waydroid: ../lxc-6.0.0/src/lxc/utils.c: run_buffer: 571 Script exited with status 126
lxc-start: waydroid: ../lxc-6.0.0/src/lxc/start.c: lxc_end: 986 Failed to run lxc.hook.post-stop for container "waydroid"
```

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Gentoo amd64

### Kernel version

6.6.30-gentoo-x86_64

### Desktop Environment

Plasma 5.27.11

### GPU

Intel Iris 12th Gen

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by cniw** [comment]
>[gbinder] WARNING: Service manager /dev/binder has died

Please try to add `psi=1` boot flag to your kernel boot loader

**Comment by IsaacMak2009** [comment]
> > [gbinder] WARNING: Service manager /dev/binder has died
> 
> Please try to add `psi=1` boot flag to your kernel boot loader

I added the `psi=1` boot flag to the kernel boot loader, but the problem persists!

**Comment by hangodek** [comment]
adding psi=1 to grub fixed the problem for me

**Comment by ljgermain** [comment]
The problem still persists for me as well after adding the `psi=1` parameter... Did anyone figure this out? I've been trying to fix this for days.

**Comment by ljgermain** [comment]
I fixed it by enabling `CONFIG_COMPAT`. For anyone with a `nomultilib` Gentoo install, this is probably the step you need to take; Waydroid depends on IA32 emulation in the kernel despite not requiring 32-bit system libraries.

**Comment by ohel** [comment]
I got the exact same problem after installing the ARM translation layer (libhoudini or libndk) using waydroid_scripts. Before that Waydroid was working. Uninstalling the translation layer doesn't solve the issue. I had to re-initialize Waydroid for it to work again.

However, after re-initializing and trying to reproduce, I am now not receiving any errors at all, but Waydroid is still not starting/visible.
