### ISSUE TITLE
Waydroid not installing / updating to 1.3.1

### ISSUE THREAD

**Issue by nanonerd-io** [waydroid/waydroid#513]
Waydroid was working right up until today when I tried to update it. Did a fresh install of Ubuntu 22.04 because I wanted to start from scratch anyways. Whether updating or installing, this is the error I'm receiving

```
Get:1 https://repo.waydro.id jammy/main all waydroid all 1.3.1 [212 kB]
Err:1 https://repo.waydro.id jammy/main all waydroid all 1.3.1
  File has unexpected size (212282 != 212270). Mirror sync in progress? [IP: 205.185.118.53 443]
  Hashes of expected file:
   - SHA256:70c974a634366070ad63b384f2b98a7a5dde7cd4938c7fba7761c65a80ffb3f3
   - SHA1:a1ef65b4cbdd750a8a94555d938b2a082524f3a0 [weak]
   - MD5Sum:ca398933faecf87b55fdbc8fc3774f57 [weak]
   - Filesize:212270 [weak]
E: Failed to fetch https://repo.waydro.id/erfan/jammy/waydroid_1.3.1_all.deb  File has unexpected size (212282 != 212270). Mirror sync in progress? [IP: 205.185.118.53 443]
   Hashes of expected file:
    - SHA256:70c974a634366070ad63b384f2b98a7a5dde7cd4938c7fba7761c65a80ffb3f3
    - SHA1:a1ef65b4cbdd750a8a94555d938b2a082524f3a0 [weak]
    - MD5Sum:ca398933faecf87b55fdbc8fc3774f57 [weak]
    - Filesize:212270 [weak]
E: Unable to fetch some archives, try running apt-get update or apt-get --fix-missing.
```

**Comment by JamiKettunen** [comment]
Fixed 4 hours after your report according to https://t.me/WayDroid/104136.

**Comment by voltrare** [comment]
Still got the same error on focal

```Get:1 https://repo.waydro.id focal/main all waydroid all 1.3.1 [212 kB]
Err:1 https://repo.waydro.id focal/main all waydroid all 1.3.1
  File has unexpected size (211972 != 211760). Mirror sync in progress? [IP: 205.185.118.53 443]
  Hashes of expected file:
   - SHA256:bc5d86a454b7551a9a544595b1fc111a5157de0fdeaf48222a5220df114c393c
   - SHA1:8b7093394e95bde2b11a09dd7f6e64da2cdc37bc [weak]
   - MD5Sum:1c54d643b3713784e4ec4e51166a66fe [weak]
   - Filesize:211760 [weak]
E: Failed to fetch https://repo.waydro.id/erfan/focal/waydroid_1.3.1_all.deb  File has unexpected size (211972 != 211760). Mirror sync in progress? [IP: 205.185.118.53 443]
   Hashes of expected file:
    - SHA256:bc5d86a454b7551a9a544595b1fc111a5157de0fdeaf48222a5220df114c393c
    - SHA1:8b7093394e95bde2b11a09dd7f6e64da2cdc37bc [weak]
    - MD5Sum:1c54d643b3713784e4ec4e51166a66fe [weak]
    - Filesize:211760 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by JamiKettunen** [comment]
And you both definitely did an `apt update` before trying?

**Comment by nanonerd-io** [comment]
Still an issue for me on Jammy. I did `sudo apt update` and still getting the same set of errors

**Comment by voltrare** [comment]
yes

> And you both definitely did an `apt update` before trying?

**Comment by wallypg** [comment]
I did the update before when failed, but I tried again now and it worked!

**Comment by aleasto** [comment]
Fixed... until the next update when it might break again. Hopefully not

**Comment by IlgazC** [comment]
It happens under Windows 11 WSL with Ubuntu focal LTS
Get: 1 https://repo.waydro.id focal/main all waydroid all 1.3.3 [214 kB]
Err https://repo.waydro.id focal/main all waydroid all 1.3.3
  Hash Sum mismatch
Hashes of expected file:
 - SHA256:331c46ef1d294bb390aff0e606070be143b66b41ffd0998bf36314082e45f3ab
 - SHA1:684ddc904c9f58234c32412673e52a41c1a3dcc3 [weak]
 - MD5Sum:1707068df6b9bb67d5c68b7c7fd8964e [weak]
 - Filesize:214184 [weak]
Hashes of received file:
 - SHA256:d0dc254af109ef0a515c8c537996d0e3c5acabeab3788cca9b19b367fc2476ee
 - SHA1:af6fcda45e070c364007a6a9875e5a2988fd766a [weak]
 - MD5Sum:e57267976a7b39f902df1ea45415042d [weak]
 - Filesize:214184 [weak]
Last modification reported: Mon, 28 Nov 2022 23:13:18 +0000

Fetched 214 kB in 2s (101 kB/s)
E: Failed to fetch https://repo.waydro.id/erfan/focal/waydroid_1.3.3_all.deb: Hash Sum mismatch
   Hashes of expected file:
    - SHA256:331c46ef1d294bb390aff0e606070be143b66b41ffd0998bf36314082e45f3ab
    - SHA1:684ddc904c9f58234c32412673e52a41c1a3dcc3 [weak]
    - MD5Sum:1707068df6b9bb67d5c68b7c7fd8964e [weak]
    - Filesize:214184 [weak]
   Hashes of received file:
    - SHA256:d0dc254af109ef0a515c8c537996d0e3c5acabeab3788cca9b19b367fc2476ee
    - SHA1:af6fcda45e070c364007a6a9875e5a2988fd766a [weak]
    - MD5Sum:e57267976a7b39f902df1ea45415042d [weak]
    - Filesize:214184 [weak]
   Last modification reported: Mon, 28 Nov 2022 23:13:18 +0000
E: Unable to fetch some packages; try '-o APT::Get::Fix-Missing=true' to continue with missing packages
