### ISSUE TITLE
host hangs when UI appears

### ISSUE THREAD

**Issue by stsp** [waydroid/waydroid#585]
**Describe the bug**
I start waydroid, and when UI appears the
notebook hangs completely. Sometimes it can
work for a while, but in most cases the hang is
instant.

**General information (please complete the following information):**
 - waydroid 1.3.3
 - Waydroid Images Version - not sure, it downloaded them automatically

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10 x64
 - GPU: AMD Cezanne
 - Kernel version: Generic 5.19.0-23
 - Host mesa version: mesa 22.2.1, renoir driver used
 - Desktop: Gnome 43

**Additional context**
I am pretty sure its related to GPU drivers.
Is there any way to try with software rendering?
I don't need games so speed is not a problem.

**Logs (please upload as file)**
Logs cannot be saved, complete hang.

**Comment by aleasto** [comment]
So you're not using Mesa on the host?

Yes you can use software rendering: https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm

**Comment by stsp** [comment]
> So you're not using Mesa on the host?

I do use mesa with renoir driver, as mentioned
in the initial report. Not sure how well the driver
is supported though, maybe it is not very common.

> Yes you can use software rendering: https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm

Thanks, with that I've got some progress.
Initially it just OOMed my notebook by quickly
draining whole 8Gb of ram and 20Gb of swap.
I increased the swap to 100Gb.
Now I can see how the mouse movements and
clicks in android UI drains swap gigabytes rather
quickly, but 100Gb seems enough, and eventually
gnome-shell crashes. Which is better than the
whole system hang.

So I did it differently.
Instead of starting full android UI, I decided to
start particular android apps - somehow they
appeared on the host collection of apps!
This almost works.
Apps start and work for some time, then crash.
Its a big progress because host is still alive and
gnome-shell is fine, so I can at least collect logs.
Attached is a "logcat" log full of errors that I don't
understand but maybe you do.

[logcat.txt](https://github.com/waydroid/waydroid/files/9996715/logcat.txt)

**Comment by raymond-nee** [comment]
Just encountered similar hang problem. Screen hangs instantly after android GUI appears.
Meanwhile the system backend seems to be normal, I can still use KDE Connect to change the music playback or run some commands, so it might just crash the display side.

**Waydroid version**: 1.3.3 with image 20221105
**Desktop info**:
OS: openSUSE Tumbleweed
DE: KDE Plasma 5.26.3
Kernel version: 6.0.8 Generic
GPU: AMD Picasso
Mesa: 22.2.3

**Comment by otboss** [comment]
Experiencing the same hang issue. Immediately after the UI launches my entire computer freezes, forcing a **hard reboot**

#### System Details:
OS: Ubuntu 22.04.1 LTS x86_64 
Kernel: 5.15.0-43-generic 
Uptime: 6 mins
Shell: bash 5.1.16
DE: GNOME 42.5
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 5800H with Radeon G 
GPU: AMD ATI 05:00.0 Cezanne 
GPU: NVIDIA GeForce RTX 3050 Ti Mobi

**Comment by stsp** [comment]
So what do we have:
`GPU: AMD Picasso` - "Meanwhile the system backend seems to be normal, I can still use KDE"
`GPU: AMD ATI 05:00.0 Cezanne` - "Immediately after the UI launches my entire computer freezes"

So only Cezanne produces the hard freeze,
for 2 people already.
Seems like time to open a bug report for renoir driver.
@raymond-nee could you please indicate the mesa driver in use?
@otboss could you please confirm the use of the "renoir" driver?

**Comment by otboss** [comment]
It would seem that there is some Renoir driver usage.

`lspci -v`

Prints

```
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne Root Complex
	Subsystem: Lenovo Renoir/Cezanne Root Complex
	Flags: fast devsel

00:00.2 IOMMU: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne IOMMU
	Subsystem: Lenovo Renoir/Cezanne IOMMU
	Flags: bus master, fast devsel, latency 0, IRQ -2147483648
	Capabilities: <access denied>

00:01.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe Dummy Host Bridge
	Flags: fast devsel, IOMMU group 0

00:01.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir PCIe GPP Bridge (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 26, IOMMU group 1
	Bus: primary=00, secondary=01, subordinate=01, sec-latency=0
	I/O behind bridge: 00003000-00003fff [size=4K]
	Memory behind bridge: d0000000-d10fffff [size=17M]
	Prefetchable memory behind bridge: 000000fb00000000-000000fc01ffffff [size=4128M]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

00:01.2 PCI bridge: Advanced Micro Devices, Inc. [AMD] Renoir/Cezanne PCIe GPP Bridge (prog-if 00 [Normal decode])
	Flags: bus master, fast devsel, latency 0, IRQ 27, IOMMU group 2
	Bus: primary=00, secondary=02, subordinate=02, sec-latency=0
	I/O behind bridge: [disabled]
	Memory behind bridge: d1800000-d18fffff [size=1M]
	Prefetchable memory behind bridge: [disabled]
	Capabilities: <access denied>
	Kernel driver in use: pcieport

...

```

**Comment by stsp** [comment]
You can see mesa driver with
`glxinfo |grep "renderer string"`
For me its:
`RENOIR (renoir, LLVM 15.0.2, DRM 3.47, 5.19.0-23-generic)`

**Comment by otboss** [comment]
Okay seeing something similar.

`glxinfo |grep "renderer string"`

Prints:

`OpenGL renderer string: AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.0-43-generic)`

**Comment by raymond-nee** [comment]
> @raymond-nee could you please indicate the mesa driver in use?

Output of glxinfo:  `Radeon Vega 10 (raven, LLVM 15.0.3, DRM 3.48, 6.0.8-1-default)`
My laptop also run into full freeze for a few times today when the Waydroid GUI shows up, the system backend is not always work. So it may not just a model-specific problem.

**Comment by stsp** [comment]
Was the freeze really hard for you,
such as you can't even switch to a kernel
console with eg Ctrl-Alt-F4?

Also everyone here can see
https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm
and switch to sw rendering.
For me that removed the hard freezes
(but the rest of the problem remained,
so nothing works)

**Comment by stsp** [comment]
Maybe we can ask @alexdeucher about
how to proceed with this amdgpu-specific
hang?
He have just joined the github, obviously to
help us. :)

**Comment by otboss** [comment]
I can confirm that I was unable to switch to another ttyl, happened to try that. Didn't work. Hard reboot was the only option. Also the steps in the link provided (https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm) worked and Waydroid started but as soon as I changed into **show-full-ui** mode it crashes. The apps appear in the drawer but they don't start when clicked

**Comment by stsp** [comment]
Yeah, that's what I have too.
But I wonder if @raymond-nee is having
such a hard freeze as the Cezanne users do.
Maybe for him the switch to kernel console
still worked?

> By the way, how can I revert the show-full-ui mode?

Not sure what revert do you mean, I just type
`waydroid show-full-ui`
in terminal and it shows. But I am just a
first-time user of waydroid.

**Comment by raymond-nee** [comment]
> Was the freeze really hard for you,\nsuch as you can't even switch to a kernel\nconsole with eg Ctrl-Alt-F4?

Confirmed, it's hard freeze. I also can't switch to tty interface. 

Software rendering doesn't work for me.

**Comment by stsp** [comment]
Seems like trying out the proprietary
AMD driver is not an option here?
https://www.amd.com/en/support/apu/amd-ryzen-processors/amd-ryzen-5-mobile-processors-radeon-graphics/amd-ryzen-5-5600u
Doesn't seem to list the proprietary driver
for linux.

**Comment by raymond-nee** [comment]
> Doesn't seem to list the proprietary driver

They have a seperate page for the Linux drivers
https://www.amd.com/en/support/linux-drivers

Although the installers are only support the enterprise/stable systems. (like RHEL/SLES/Ubuntu)

**Comment by stsp** [comment]
I am aware of that URL, but it only
seems to list the Radeon cards.
Are you sure APUs are supported there?

**Comment by raymond-nee** [comment]
> Are you sure APUs are supported there?

Seems like it mainly supports workstation cards. 
Most APUs are only have open source implementation.

**Comment by otboss** [comment]
@wsippel How does one go about disabling multi-window mode? After I enabled that Waydroid doesn't event launch anymore.

**Comment by raymond-nee** [comment]
> but the system is clearly still running. I could still hear a Youtube video running in the background. Happened three times in a row.

@wsippel  The problem most likely on the display-related side, but as some of us just written above, there still a chance that whole system could be halted. (I can also hear the music playback and change it by KDE Connect when at first few freezes)

**Comment by wsippel** [comment]
> @wsippel How does one go about disabling multi-window mode? After I enabled that Waydroid doesn't event launch anymore.

`waydroid prop set persist.waydroid.multi_windows false` should work I think.

**Comment by ELIE1105** [comment]
same issue too,
waydroid 1.3.3 with automatic image installation
I5 8250U
HD Graphics 620

**Comment by Shaarigan** [comment]
Experienced same today:

Lenovo IdeaPad Flex 5 14ALC - Zorin OS 16.2
AMD Ryzen™ 5 5500U Prozessor (Hexa-Core) 
16 GB DDR4-3200 SO-DIMM
AMD Radeon RX Vega 7

It also happened sometimes that even on full screen mode Waydroid caused the GNOME shell to hang. I opened the Settings App from the app menu and it opened for whatever reason twice, then I pressed the back button to get to the Android main screen and it did not respond anymore. Had to hard reset the device. Seems to me as if the rendering of the main screen causes some trouble. For whatever reason the App icons also look weird, they have there color inverted even if the settings are turned off. 

Whatever, windowed mode doesn't work at all for me. It doesn't even render the window frame and title bar but freezes immediately on a fresh Zorin installation

**Comment by skoruppa** [comment]
I have the same issue. With `waydroid prop set persist.waydroid.multi_windows true` Waydroid is unusable. Opening an app hangs my whole system for some time. If I wait long enough, I can use my system again, but the opened app is not responsible. 

Ubuntu 22.04
OpenGL renderer string: Mesa Intel(R) UHD Graphics (CML GT2)

**Comment by legend1148** [comment]
Can also confirm freezing for my setup. Just Ditropan hopped from Manjaro KDE and was not having this problem but now I am on:
Ubuntu 22.04
Intel I5-11400 (igpu disabled by bios)
RX 6400 
24GB RAM

GLX device AMD BEIGE_GOBY (LLVM 13.0.1)
Version 22.0.5

**Comment by aleasto** [comment]
I believe this is fixed in the latest vendor images (2023-02-04). Can you confirm?

**Comment by stsp** [comment]
Don't want to try with hw rendering
enabled to not get my notebook hang.
But with SW rendering all is still the
same: crash after a few mouse clicks,
OOMs up to killing gnome-shell, and
so on. From ~10 starts of a simple
mobile app, only once I was able to get
into its initial prompt and type a few digits
of a phone number, before it crashed.

**Comment by stsp** [comment]
A few clicks in a "full ui" also lead to
a crash. So it doesn't even matter if
the hw-accel hang is fixed or not.

**Comment by aleasto** [comment]
Can you share the output of `sudo waydroid shell getprop` ?

**Comment by stsp** [comment]
[a.txt](https://github.com/waydroid/waydroid/files/10676278/a.txt)
Sure, here it is.

**Comment by aleasto** [comment]
I see you are using images from November 2022, please update your waydroid images: `sudo waydroid upgrade` as this was only just fixed (hopefully)

**Comment by stsp** [comment]
Thanks, I thought the plain system updates
are enough. I am a newbie to waydroid, but
I guess if it could update itself together with
system updates, things would be easier for
users. :)
Trying now...

**Comment by legend1148** [comment]
> I believe this is fixed in the latest vendor images (2023-02-04). Can you confirm?

Just updated the Waydroid system binaries and the image and it is working for me now.

**Comment by stsp** [comment]
I can also confirm that it works much
better now and doesn't seem to hang
even w/o disabling GPU rendering.
So as an opener of that ticket, let me
close it.
What was the fix, is there any announce
of it?
Thanks!

**Comment by aleasto** [comment]
You may consider this the announcement. Thanks for confirming.

**Comment by stsp** [comment]
This announcement doesn't tell me
what was fixed. Changelog usually
does it better, but oh well. :)

**Comment by aleasto** [comment]
https://github.com/waydroid/android_hardware_waydroid/commit/91003449fecef10d0bb6055dbd5c6015fd50626f fixes the memory leak that lead to OOM on software rendering
https://github.com/waydroid/android_vendor_waydroid/commit/816c894b09fe4d26345b0b7ca7d1e0a4923b7ca5 fixes multi_windows crashing on software rendering
https://github.com/waydroid/android_hardware_waydroid/commit/6aafe20573722d230d35601ccf2ccae73d4e54f2 removes the improper use of `/sys/kernel/debug/sync/sw_sync` that hanged waydroid and may deadlock the kernel

**Comment by stsp** [comment]
Thanks, great work.

**Comment by raymond-nee** [comment]
Just updated the image and it work as expected. Thanks for the great work.

**Comment by RichardJECooke** [comment]
Still happening on Ubuntu 24.04 with whatever the latest Waydroid version is.
