### ISSUE TITLE
JW Library: "failed to create temp directory"

### ISSUE THREAD

**Issue by yajo** [waydroid/waydroid#699]
**Describe the bug**
The app [JW Library](https://play.google.com/store/apps/details?id=org.jw.jwlibrary.mobile&gl=us) doesn't work as expected.

**Screencast**

To reproduce it:

1. Install JW Library (you can install it without an app store following [these instructions](https://www.jw.org/en/online-help/jw-library/android/manually-install-jw-library-android/)).
2. Download a jwpub file, such as [this one](https://download-a.akamaihd.net/files/media_periodical/45/wp_E_202105.jwpub).
3. Open it with JW Library.

See it live:

https://user-images.githubusercontent.com/973709/212749169-f5af7f2e-8cf7-4c03-90b6-d7210081419f.mp4

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.4
 - Waydroid Images Version 18.1-20230114-VANILLA-waydroid_x86_64

**Desktop (please complete the following information):**
 - OS: Fedora Linux 37.20230115.0 (Silverblue)
 - GPU: AMD Ryzen™ 7 5700U with Radeon™ Graphics × 16
 - Kernel version: kernel-6.1.5-200.fc37.x86_64
 - Host mesa version: 22.3.3
 - Desktop: Gnome 43.2

**Additional context**
The app is expected to open jwpub files correctly. That's what it does in a normal Android phone.

**Logs (please upload as file)**

 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`: [waydrod_base.prop.txt](https://github.com/waydroid/waydroid/files/10428694/waydrod_base.prop.txt)
 - Output of `waydroid log`: [waydroid log.txt](https://github.com/waydroid/waydroid/files/10428709/waydroid.log.txt)
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services: [waydroid logcat.txt](https://github.com/waydroid/waydroid/files/10428716/waydroid.logcat.txt)

**Comment by electrikjesus** [comment]
If you are not running this on an ARM64 device, I am wondering is JW Library is missing libs for x86_64?

**Comment by yajo** [comment]
I downloaded the apk and unzipped it. It does contain a `lib/x86_64` folder with some libraries.

**Comment by electrikjesus** [comment]
Can you please grab a log while it is crashing?

**Comment by yajo** [comment]
`waydroid log` printed out nothing while it was crashing. `sudo waydroid logcat` printed this:

```
01-18 07:30:47.445  2124  2124 D QuickViewIntentBuilder: Preparing intent for doc:primary:Download/wp_E_202105(2).jwpub
01-18 07:30:47.446   267   632 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=content://com.android.externalstorage.documents/document/primary:Download/wp_E_202105(2).jwpub typ=application/octet-stream flg=0x20000003 cmp=org.jw.jwlibrary.mobile/.activity.SiloContainer} from uid 10086
01-18 07:30:47.454   267   287 I ActivityManager: Killing 681:com.android.settings/1000 (adj 975): empty #17
01-18 07:30:47.454   267   295 W libprocessgroup: Failed to open process cgroup uid 1000 pid 681: Permission denied
01-18 07:30:47.454   267   295 E libprocessgroup: Error encountered killing process cgroup uid 1000 pid 681: Permission denied
01-18 07:30:47.461    65    65 I Zygote  : Process 681 exited due to signal 9 (Killed)
01-18 07:30:47.463   267   287 W ActivityManager: setHasOverlayUi called on unknown pid: 681
01-18 07:30:47.475  1054  1054 W ContextImpl: Failed to ensure /storage/emulated/0/Android/data/org.jw.jwlibrary.mobile/cache: android.os.ServiceSpecificException:  (code -1)
01-18 07:30:47.475  1054  1054 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10140; state: ENABLED
01-18 07:30:47.502   267   292 W system_server: Insufficient pre-allocated space to mmap vdex.
01-18 07:30:47.534   267   327 I InputDispatcher: Dropping event because there is no touched foreground window in display 0 or gesture monitor to receive it.
01-18 07:30:50.983   267   312 W NotificationService: Toast already killed. pkg=org.jw.jwlibrary.mobile token=android.os.BinderProxy@afc6715
01-18 07:30:47.534   267   327 I InputDispatcher: Dropping event because there is no touched foreground window in display 0 or gesture monitor to receive it.
01-18 07:30:52.572  2124  2140 W System  : A resource failed to call release. 
```

**Comment by n1lby73** [comment]
@yajo do videos in the jw library app now work properly in waydroid

**Comment by yajo** [comment]
Yes, they both download and play well AFAICS.

**Comment by n1lby73** [comment]
would give it a try again when on pc, very busy with college activities lately

**Comment by amarintj1986** [comment]
Just to confirm the problem. I have the same issue trying to upload a backup with JW Library. It can´t restore it, just displays the message: "failed  to create a temp file" I have Ubuntu 22.04.1,, GNOME 42.5 Mesa Intel® UHD Graphics, Intel® Core™ i5-1035G1, Waydroid 1.3.4 with GAPPS

**Comment by yajo** [comment]
El sáb, 21 de ene de 2023 a las 23:03:16 PM, n1lby73 
***@***.***> escribió:
> @yajo <https://github.com/yajo> what version are you running on, just 
> tried it now audio working perfectly but not video
> 

I'm using JW Library 13.3 (221490)

**Comment by yajo** [comment]
has there been any progress on this subject? Or is there any further info I can provide? Thanks!

**Comment by amarintj1986** [comment]
Hello. I just want to confirm that I updated waydroid today (30/4/2023) and the problem restoring a backup on JW  Library was solved. Thanks a lot for your work

**Comment by yajo** [comment]
What version are you using?

**Comment by amarintj1986** [comment]
I'm using waydroid version 1.4.1 on Ubuntu 22.04.2

**Comment by iTomKo** [comment]
For anyone having this issue with this app in particular, here's my solution (requires adb + root):
`adb shell`
`su`
`cd /storage/emulated/0/Android/data/org.jw.jwlibrary.mobile`

From my logs, I've figured out, that its missing its cache folder, in that case you have to create it and ensure proper permission.
Beforehand we need to know the owner of the app directory.
`ls -la`
It will look like:
`drwxrws---  6 u0_a535  ext_data_rw 3488 2025-06-20 09:48 files`
We are interested in the u0_a... part.

`mkdir cache # Creates the folder`
`chown u0_a535:ext_data_rw cache # Put the correct owner here`
`chmod 0770 cache # Sets correct folder permissions`

Optional - checking SELinux:
`chcon u:object_r:app_data_file:s0 cache`

Afterwards you should be able to restore your backup!
Hope that helps and that I'm not necroposting :D

**Comment by graeycloak** [comment]
Small update from my end.  I had the same issue, and the fix from @iTomKo worked (mostly).  I no longer got the error, but the backups and other imports were still not actually happening.  Just the app would load, but nothing further.  Running:

chmod 2770 

Seems to have done the trick.  It matches the permissions on the files, and I'm able to import new publications as well as restore backups.

**Comment by Jo-Kal12** [comment]
Hi, i follow your instruction but it can't do. I have try use chmod 0770 and 2770 but not working. How i can resolve? 

@graeycloak rectification, in my case, i delate app and all folder in data/org.jw.jwlibrary.mobile. After i use all comand by @iTomKo and when i arrive a "chmod 0770 cache" after use this command i use "chmod 2770 cache". Initially I only used the first command but it didn't work. Using the first one and then the second one worked. THANKS!!!! 

Sorry for my english!
