### ISSUE TITLE
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

### ISSUE THREAD

**Issue by yichuang-zh** [waydroid/waydroid#903]
**Describe the bug**
After run command "waydroid session start", the terminal shows:
  `[19:24:13] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
`

Here is the log:
`
(001755) [09:31:46] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(001755) [09:31:46] Save config: /var/lib/waydroid/waydroid.cfg
(001755) [09:31:48] % mkdir -p /var/lib/waydroid/cache_http
(001755) [09:31:48] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230422-GAPPS-waydroid_x86_64-system.zip/download
(001755) [11:07:20] Validating system image
(001755) [11:07:21] Extracting to /var/lib/waydroid/images
(001755) [11:07:27] Save config: /var/lib/waydroid/waydroid.cfg
(001755) [11:07:31] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20230422-MAINLINE-waydroid_x86_64-vendor.zip/download
(001755) [11:25:04] Validating vendor image
(001755) [11:25:04] Extracting to /var/lib/waydroid/images
(001755) [11:25:06] Save config: /var/lib/waydroid/waydroid.cfg
(001755) [11:25:06] % modprobe -q ashmem_linux
(001755) [11:25:06] % lxc-info --version
5.0.2
(001755) [11:25:06] % mkdir -p /var/lib/waydroid/lxc/waydroid
(001755) [11:25:06] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(001755) [11:25:06] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(001755) [11:25:06] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(001755) [11:25:06] % aa-enabled --quiet
(001755) [11:25:06] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(001755) [11:25:06] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(000543) [11:35:15] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000543) [11:35:15] % modprobe -q ashmem_linux
(000543) [11:35:15] % chmod 666 -R /dev/anbox-binder
(000543) [11:35:15] % chmod 666 -R /dev/anbox-vndbinder
(000543) [11:35:15] % chmod 666 -R /dev/anbox-hwbinder
(001735) [11:35:15] Starting waydroid session
(000543) [11:35:15] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 91: -I: not found
Failed to setup waydroid-net.
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 213: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 214: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 215: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 216: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 217: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 218: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 219: -t: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 220: -t: not found
(000543) [11:35:15] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000543) [11:35:15] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(001735) [11:35:15] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(001735) [11:35:15] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(000543) [11:35:26] Hardware service is not even started
(000543) [11:35:26] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000543) [11:35:26] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(000543) [11:35:26] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(000541) [18:09:53] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000541) [18:09:53] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(000541) [18:09:53] % modprobe -q ashmem_linux
(000541) [18:09:53] % chmod 666 -R /dev/anbox-binder
(000541) [18:09:53] % chmod 666 -R /dev/anbox-vndbinder
(000541) [18:09:53] % chmod 666 -R /dev/anbox-hwbinder
(000541) [18:22:56] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 91: -I: not found
Failed to setup waydroid-net.
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 213: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 214: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 215: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 216: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 217: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 218: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 219: -t: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 220: -t: not found
(000541) [18:22:56] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000541) [18:22:56] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(003040) [18:22:56] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(003040) [18:22:56] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(003096) [18:23:09] Starting waydroid session
(000541) [18:23:09] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 91: -I: not found
Failed to setup waydroid-net.
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 213: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 214: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 215: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 216: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 217: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 218: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 219: -t: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 220: -t: not found
(000541) [18:23:09] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000541) [18:23:09] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(003096) [18:23:09] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(003096) [18:23:09] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(000541) [18:38:17] Hardware service is not even started
(000541) [18:38:17] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000541) [18:38:17] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(000541) [18:38:17] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(000542) [18:48:36] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000542) [18:48:36] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(000542) [18:48:36] % modprobe -q ashmem_linux
(000542) [18:48:36] % chmod 666 -R /dev/anbox-binder
(000542) [18:48:36] % chmod 666 -R /dev/anbox-vndbinder
(000542) [18:48:36] % chmod 666 -R /dev/anbox-hwbinder
(002962) [18:52:27] Starting waydroid session
(000542) [18:52:27] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 91: -I: not found
Failed to setup waydroid-net.
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 213: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 214: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 215: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 216: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 217: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 218: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 219: -t: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 220: -t: not found
(000542) [18:52:28] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000542) [18:52:28] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(002962) [18:52:28] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(002962) [18:52:28] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(000542) [18:57:17] Hardware service is not even started
(000542) [18:57:17] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000542) [18:57:17] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(000542) [18:57:17] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(003296) [18:57:17] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(003296) [18:57:17] % modprobe -q ashmem_linux
(003296) [18:57:17] % chmod 666 -R /dev/anbox-binder
(003296) [18:57:17] % chmod 666 -R /dev/anbox-vndbinder
(003296) [18:57:17] % chmod 666 -R /dev/anbox-hwbinder
(003328) [18:58:29] Starting waydroid session
(003296) [18:58:29] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 91: -I: not found
Failed to setup waydroid-net.
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 213: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 214: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 215: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 216: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 217: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 218: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 219: -t: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 220: -t: not found
(003296) [18:58:29] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(003296) [18:58:29] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(003328) [18:58:29] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(003328) [18:58:29] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(003296) [18:58:39] Hardware service is not even started
(003296) [18:58:39] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(003296) [18:58:39] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(003296) [18:58:39] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(000543) [18:58:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000543) [18:58:45] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(000543) [18:58:45] % modprobe -q ashmem_linux
(000543) [18:58:45] % chmod 666 -R /dev/anbox-binder
(000543) [18:58:45] % chmod 666 -R /dev/anbox-vndbinder
(000543) [18:58:45] % chmod 666 -R /dev/anbox-hwbinder
(003515) [19:06:13] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(003515) [19:06:13] % modprobe -q ashmem_linux
(003515) [19:06:13] % lxc-info --version
5.0.2
(003515) [19:06:13] % mkdir -p /var/lib/waydroid/lxc/waydroid
(003515) [19:06:13] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(003515) [19:06:13] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(003515) [19:06:13] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(003515) [19:06:13] % aa-enabled --quiet
(003515) [19:06:13] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(003515) [19:06:13] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(000543) [19:06:22] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 91: -I: not found
Failed to setup waydroid-net.
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 213: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 214: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 215: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 216: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 217: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 218: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 219: -t: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 220: -t: not found
(000543) [19:06:22] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000543) [19:06:22] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(003527) [19:06:22] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(003527) [19:06:22] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(003788) [19:10:01] Run waydroid -h for usage information.
(000543) [19:24:13] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 91: -I: not found
Failed to setup waydroid-net.
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 213: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 214: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 215: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 216: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 217: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 218: -D: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 219: -t: not found
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 220: -t: not found
(000543) [19:24:13] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000543) [19:24:13] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(005535) [19:24:13] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(005535) [19:24:13] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
`

**Screenshots**

**General information (please complete the following information):**
 - $ waydroid -V
1.4.1

 - Waydroid Images Version:
20230422-GAPPS

**Desktop (please complete the following information):**
 - OS: Debian12 bookworm (virtual machine) [Host: Debian12 bookworm + gnome]
 - GPU: AMD 5800x
 - Kernel version(virtual machine): uname -r 
 6.1.0-8-amd64
 - Kernel version(host machine): uname -r 
 6.1.0-8-amd64

 - Host mesa version: glxinfo | grep "OpenGL verion"
OpenGL version string: 4.6.0 NVIDIA 525.105.17

 - Host Desktop: Gnome 43.4

**Smartphone
No.

**Additional context**
I had installed a vmGuest: debian12 bookworm with gnome on my host(debian12 too), and installed waydroid on my vmGuest.

**Logs (please upload as file)**
 - Prop file:
[waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/11463593/waydroid_base.prop.txt)

 - Log file:
[waydroid.log.txt](https://github.com/waydroid/waydroid/files/11463595/waydroid.log.txt)

 
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`:
[dmesg.txt](https://github.com/waydroid/waydroid/files/11463603/dmesg.txt)

**Comment by labo-China** [comment]
Getting the same problem here, running on ArchLinux with Kernel: 6.3.1-zen1-1-zen
This is my log

(023860) [22:38:41] Starting waydroid session
(019537) [22:38:41] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Warning: Extension udp revision 0 not supported, missing kernel module?
iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Failed to setup waydroid-net.
Warning: Extension udp revision 0 not supported, missing kernel module?
iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Warning: Extension tcp revision 0 not supported, missing kernel module?
iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Warning: Extension udp revision 0 not supported, missing kernel module?
iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Warning: Extension tcp revision 0 not supported, missing kernel module?
iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
iptables v1.8.9 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables v1.8.9 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables v1.8.9 (legacy): can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
(019537) [22:38:41] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(019537) [22:38:41] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(023860) [22:38:41] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

**Comment by FranGamer1892** [comment]
I am having the exact same issue as [yichuang-zh](https://github.com/yichuang-zh).

**Comment by FranGamer1892** [comment]
Fixed it by installing "iptables". I am surprised it was not in Debian bookworm already.

**Comment by yichuang-zh** [comment]
I 

> Fixed it by installing "iptables". I am surprised it was not in Debian bookworm already.

I installed iptables the way you did, but it created a new problem:

`~$ waydroid session start
[06:59:59] Failed to start Clipboard manager service, check logs
[07:00:48] Android with user 0 is ready

`
Here is the log file:

[waydroid.log](https://github.com/waydroid/waydroid/files/11482566/waydroid.log)

**Comment by FranGamer1892** [comment]
How about running "waydroid show-full-ui" instead? I get similar if not
exactly the same output yet it works.

**Comment by yichuang-zh** [comment]
The output is:
`Starting waydroid session
Failed to start Clipboard manager service, check logs`

Then nothing happened.

[waydroid.log](https://github.com/waydroid/waydroid/files/11492671/waydroid.log)

**Comment by iTzVoko** [comment]
> Fixed it by installing "iptables". I am surprised it was not in Debian bookworm already.

Thank you. I'm surprised that this package fixed the issue successfully.

**Comment by ckcr4lyf** [comment]
FYI, I had the same error message, but from the logs I got:

```
(3983835) [12:23:51] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0

dnsmasq: failed to create listening socket for 192.168.240.1: Address already in use
Failed to setup waydroid-net.
Failed to setup waydroid-net.
```

Turns out it needs to bind something on port 53, and I had piHole setup to listen on `0.0.0.0:53` . Changing piHole settings allowed me to start it.

**Comment by TNTBOMBOM** [comment]
> FYI, I had the same error message, but from the logs I got:
> 
> ```
> (3983835) [12:23:51] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
> vnic is waydroid0
> 
> dnsmasq: failed to create listening socket for 192.168.240.1: Address already in use
> Failed to setup waydroid-net.
> Failed to setup waydroid-net.
> ```
> 
> Turns out it needs to bind something on port 53, and I had piHole setup to listen on `0.0.0.0:53` . Changing piHole settings allowed me to start it.

Unrelated to the ticket issue. Nevertheless waydroid is another anbox which is dead.

**Comment by BakaJzon** [comment]
My host machine powered off due to power outage. Now, I can't launch waydroid anymore.
This is the output of `ip addr show`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: enp4s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000
    link/ether b0:25:aa:58:ea:fe brd ff:ff:ff:ff:ff:ff
3: wlo1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c8:58:c0:23:a0:23 brd ff:ff:ff:ff:ff:ff
    altname wlp0s20f3
    inet 192.168.10.5/24 brd 192.168.10.255 scope global dynamic noprefixroute wlo1
       valid_lft 86180sec preferred_lft 86180sec
    inet6 fe80::9322:293a:bc3b:b675/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
[waydroid.log](https://github.com/waydroid/waydroid/files/12385246/waydroid.log)

**Comment by ckcr4lyf** [comment]
> This is the output of `ip addr show`

How about the output of `netstat -ntlp | grep 53` ?

**Comment by BakaJzon** [comment]
> How about the output of `netstat -ntlp | grep 53` ?
Nothing here, since virtual network device `waydroid0` was missing

**Comment by ckcr4lyf** [comment]
> Nothing here, since virtual network device `waydroid0` was missing

Even without that device, it is possible some app on your machine is bound to `0.0.0.0:53` , so when `waydroid0` interface is made, port 53 is already bound to by this guy, and then dnsmasq within waydroid fails to start.

**Comment by BakaJzon** [comment]
```
(000724) [17:16:09] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0

dnsmasq: failed to create listening socket for 192.168.240.1: Address already in use
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(000724) [17:16:09] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000724) [17:16:09] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(002517) [17:16:09] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(002517) [17:16:09] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(002558) [17:16:21] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(002558) [17:16:21] *** output passed to waydroid stdout, not to this log ***
```

**Comment by ckcr4lyf** [comment]
@BakaJzon on your host system check if anything is listening on port 53. That can cause issues.

**Comment by BakaJzon** [comment]
I'm pretty sure there‘s nothing listening on it!
```
[xxx@xxx ~]$ ss -ntlp | grep 53
[xxx@xxx ~]$ waydroid session start
[19:06:13] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
```

**Comment by ckcr4lyf** [comment]
@GSI from your logs, the error is different to `dnsmasq: failed to create listening socket for 192.168.240.1: Address already in use` , which is related to the port 53 thing.

The iptables errors:

```
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables v1.8.9 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain POSTROUTING
Failed to setup waydroid-net.
Warning: Extension udp revision 0 not supported, missing kernel module?
```

seem more like some problem in your Kernel. Can you try it on a "mainstream" distribution and see if it makes a difference? Or try just using iptables

**Comment by GSI** [comment]
> Can you try it on a "mainstream" distribution

If I don't need a graphical environment, I could try to replicate the issue on a remote Alpine machine, which is the next-closest thing to pmOS and still "mainstream". Anything else doesn't have a Kernel with binderfs ...

> Or try just using iptables

How would I do that?

**Comment by ckcr4lyf** [comment]
> How would I do that?

If you've a terminal in your OS, you can try configuring the iptables firewall, and or see if it even exists? 

By mainstream I don't mean graphical at all, it could be Ubuntu / Debian pure TTY/headless even. But the error seems more to be a problem with the distribution not having iptables (or netfilter)

**Comment by GSI** [comment]
Oh. I highly doubt the issue would be reproducible in Debian and its direct derivatives - otherwise this issue would likely have many more participants.

Is there anything I may run manually to help debug on the current system?

For now, here is some more information about environment:

    # iptables -V
    iptables v1.8.9 (nf_tables)
    
    # nft -v
    nftables v1.0.8 (Old Doc Yak #2)
    
    # iptables -L
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination
    
    Chain FORWARD (policy ACCEPT)
    target     prot opt source               destination
    
    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination

**Comment by GSI** [comment]
I just cross-checked with another system also running postmarketOS that's running Kernel **6.4.14**. The issue is not present there.

All versions (nft 1.0.8, iptables 1.8.9, waydroid 1.4.1) - and actually pretty much the entire installation - are exactly the same.

Are there any kernel modules I should watch out for (`lsusb`)?

**Comment by ckcr4lyf** [comment]
Not sure personally, I think opening a bug report in your operating system's bug tracker may be a place to start.

**Comment by GSI** [comment]
After trying several variants of one of the failing commands (`iptables -w -I INPUT -i waydroid0 -p udp --dport 67 -j ACCEPT`) I found out that **the issue is resolved** by installing the `iptables-legacy` package.

Its version is shown as **iptables v1.8.9 (legacy)**. Maybe there's a way to make this work with `iptables v1.8.9 (nf_tables)` too. Otherwise, maybe `waydroid-net.sh` could perform a check and output a meaningful error message based on it.

**Comment by wold9168** [comment]
same problem.
waydroid version is `1.4.2`.
iptables version is `1.8.9(legacy)`.
Nothing has been changed after the last normal shutdown (of the waydroid), except the proxy.
But after I restore the proxy setting, waydroid still doesn't work.

**Comment by wold9168** [comment]
> same problem. waydroid version is `1.4.2`. iptables version is `1.8.9(legacy)`. Nothing has been changed after the last normal shutdown (of the waydroid), except the proxy. But after I restore the proxy setting, waydroid still doesn't work.
> 
> Distro is `Arch Linux`, DE is `Plasma 5.27.9 (X11)`. Waydroid used to run in weston.

OK, even if nothing in my computer has been changed, it works again.
And I don't know why.
weird......

**Comment by NJBA** [comment]
> Fixed it by installing "iptables". I am surprised it was not in Debian bookworm already.

How to use Iptables??

**Comment by lambdadeltakay** [comment]
Also having this issue which is odd because before waydroid started but with no internet

**Comment by BrandowLucas** [comment]
@lambdadeltakay I experienced the exactly same as you.

**Comment by kaitlynkittyy** [comment]
I'm experiencing something similar, and there's a chance it's related to ipv6 being disabled on my system, although I'm not sure.

```
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: line 154: /proc/sys/net/ipv6/conf/waydroid0/accept_dad: No such file or directory

dnsmasq: failed to create listening socket for 192.168.240.1: Address already in use
Failed to setup waydroid-net.
Failed to setup waydroid-net.
```

**Comment by ckcr4lyf** [comment]
@kaitlynkittyy can you use netstat to see listening ports?

**Comment by kaitlynkittyy** [comment]
> @kaitlynkittyy can you use netstat to see listening ports?

There are quite a few(and I mean a LOT), but nothing on that specific address. 

Also i was able to resolve this issue for myself just now by commenting out line 154 of the script and stopping the dnsmasq service

**Comment by ckcr4lyf** [comment]
To be clear, there doesn't need to be something on that address, since it could also be `0.0.0.0` (which would mean on any new interface/address automatically)

**Comment by kaitlynkittyy** [comment]
> To be clear, there doesn't need to be something on that address, since it could also be `0.0.0.0` (which would mean on any new interface/address automatically)

True, I had forgotten that, but there's still nothing on 0.0.0.0 either.

**Comment by RickMintEC** [comment]
Hey @yichuang-zh @kaitlynkittyy @ckcr4lyf @lambdadeltakay @wold9168 In Debian 12 sudo apt remove --purge bind9-* and sudo apt remove --purge bind9 dnsutils systemd-resolved dnsmasq luego waydroid run 0 problems.

**Comment by PackageInstaller** [comment]
> ```
> ❯ sudo -E ss -nulp | grep 53
> [sudo] password for i.want.to.believe: 
> UNCONN 0      0                               0.0.0.0:5353       0.0.0.0:*    users:(("avahi-daemon",pid=1602,fd=11))    
> UNCONN 0      0                            127.2.0.17:53         0.0.0.0:*    users:((".v2ray-wrapped",pid=2279,fd=11))  
> UNCONN 0      0                                     *:53               *:*    users:((".v2ray-wrapped",pid=2279,fd=9))
> ```
> 
> It works fine after stopping v2raya

thx,bro,its solved my problem

**Comment by kaitlynkittyy** [comment]
> I found that the script fails at
> 
> ```shell
>     dnsmasq $LXC_DHCP_CONFILE_ARG $LXC_DOMAIN_ARG $LXC_DHCP_PING_ARG -u ${DNSMASQ_USER} \
>             --strict-order --bind-interfaces --pid-file="${varrun}"/dnsmasq.pid \
>             --listen-address ${LXC_ADDR} --dhcp-range ${LXC_DHCP_RANGE} \
>             --dhcp-lease-max=${LXC_DHCP_MAX} --dhcp-no-override \
>             --except-interface=lo --interface=${LXC_BRIDGE} \
>             --dhcp-leasefile="${varlib}"/misc/dnsmasq.${LXC_BRIDGE}.leases \
>             --dhcp-authoritative $LXC_IPV6_ARG # || cleanup
> ```
> 
> It seems that this command fails on my computer when dnsmasq on my hostOS and WayDroid want to "take care of" `waydroid0` both.
> 
> After I add a line of `except-interface=waydroid0` to `/etc/dnsmasq.conf` on my host OS, killing and restarting dnsmasq on my hostOS again, then running `waydroid show-full-ui`, now my hostOS and WayDroid container have network connection and are able to handle domains both.

This fixed it for me under one condition, dnsmasq CANNOT be running before I launch waydroid, or it entirely fails. (which in my use case is completely broken, as I need dnsmasq running always.)

**Comment by Strykar** [comment]
So, is there a way for this to co-exist with an existing dnsmasq install?
```
$ waydroid show-full-ui
[05:43:04] Starting waydroid session
[05:43:04] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

$ /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
RTNETLINK answers: Operation not permitted
Failed to setup waydroid-net.

$ sudo bash -x /usr/lib/waydroid/data/scripts/waydroid-net.sh start
+ varrun=/run/waydroid-lxc
+ varlib=/var/lib
+ net_link_key=lxc.net.0.link
+ case "$(lxc-info --version)" in
++ lxc-info --version
++ awk '$1 == "lxc.net.0.link" {print $3}' /var/lib/waydroid/lxc/waydroid/config
+ vnic=waydroid0
+ : waydroid0
+ '[' waydroid0 '!=' waydroid0 ']'
+ echo 'vnic is waydroid0'
vnic is waydroid0
+ USE_LXC_BRIDGE=true
+ LXC_BRIDGE=waydroid0
+ LXC_BRIDGE_MAC=00:16:3e:00:00:01
+ LXC_ADDR=192.168.240.1
+ LXC_NETMASK=255.255.255.0
+ LXC_NETWORK=192.168.240.0/24
+ LXC_DHCP_RANGE=192.168.240.2,192.168.240.254
+ LXC_DHCP_MAX=253
+ LXC_DHCP_CONFILE=
+ LXC_DHCP_PING=true
+ LXC_DOMAIN=
+ LXC_USE_NFT=true
+ LXC_IPV6_ADDR=
+ LXC_IPV6_MASK=
+ LXC_IPV6_NETWORK=
+ LXC_IPV6_NAT=false
++ command -v iptables-legacy
+ IPTABLES_BIN=/usr/bin/iptables-legacy
+ '[' '!' -n /usr/bin/iptables-legacy ']'
++ command -v ip6tables-legacy
+ IP6TABLES_BIN=/usr/bin/ip6tables-legacy
+ '[' '!' -n /usr/bin/ip6tables-legacy ']'
++ command -v nft
+ NFT=/usr/bin/nft
+ use_nft
+ '[' -n /usr/bin/nft ']'
+ nft list ruleset
+ '[' true = true ']'
+ case "$1" in
+ start
+ '[' xtrue = xtrue ']'
+ '[' '!' -f /run/waydroid-lxc/network_up ']'
+ '[' -d /sys/class/net/waydroid0 ']'
+ FAILED=1
+ trap cleanup EXIT HUP INT TERM
+ set -e
+ '[' '!' -d /sys/class/net/waydroid0 ']'
+ ip link add dev waydroid0 type bridge
+ echo 1
+ echo 0
+ '[' '!' -d /run/waydroid-lxc ']'
+ _ifup
++ _netmask2cidr 255.255.255.0
++ local x=0
++ set -- '0^^^128^192^224^240^248^252^254^' 24 0
++ x=
++ echo 24
+ MASK=24
+ CIDR_ADDR=192.168.240.1/24
+ ip addr add 192.168.240.1/24 broadcast + dev waydroid0
+ ip link set dev waydroid0 address 00:16:3e:00:00:01
+ ip link set dev waydroid0 up
+ use_nft
+ '[' -n /usr/bin/nft ']'
+ nft list ruleset
+ '[' true = true ']'
+ start_nftables
+ start_ipv6
+ LXC_IPV6_ARG=
+ '[' -n '' ']'
+ NFT_RULESET=
+ '[' -n '' ']'
+ NFT_RULESET=';
add table inet lxc;
flush table inet lxc;
add chain inet lxc input { type filter hook input priority 0; };
add rule inet lxc input iifname waydroid0 udp dport { 53, 67 } accept;
add rule inet lxc input iifname waydroid0 tcp dport { 53, 67 } accept;
add chain inet lxc forward { type filter hook forward priority 0; };
add rule inet lxc forward iifname waydroid0 accept;
add rule inet lxc forward oifname waydroid0 accept;
add table ip lxc;
flush table ip lxc;
add chain ip lxc postrouting { type nat hook postrouting priority 100; };
add rule ip lxc postrouting ip saddr 192.168.240.0/24 ip daddr != 192.168.240.0/24 counter masquerade'
+ nft ';
add table inet lxc;
flush table inet lxc;
add chain inet lxc input { type filter hook input priority 0; };
add rule inet lxc input iifname waydroid0 udp dport { 53, 67 } accept;
add rule inet lxc input iifname waydroid0 tcp dport { 53, 67 } accept;
add chain inet lxc forward { type filter hook forward priority 0; };
add rule inet lxc forward iifname waydroid0 accept;
add rule inet lxc forward oifname waydroid0 accept;
add table ip lxc;
flush table ip lxc;
add chain ip lxc postrouting { type nat hook postrouting priority 100; };
add rule ip lxc postrouting ip saddr 192.168.240.0/24 ip daddr != 192.168.240.0/24 counter masquerade'
+ LXC_DOMAIN_ARG=
+ '[' -n '' ']'
+ LXC_DHCP_CONFILE_ARG=--conf-file=/dev/null
+ for DNSMASQ_USER in lxc-dnsmasq dnsmasq nobody
+ getent passwd lxc-dnsmasq
+ for DNSMASQ_USER in lxc-dnsmasq dnsmasq nobody
+ getent passwd dnsmasq
+ for DNSMASQ_USER in lxc-dnsmasq dnsmasq nobody
+ getent passwd nobody
+ break
+ LXC_DHCP_PING_ARG=
+ '[' xtrue = xfalse ']'
+ '[' '!' -d /var/lib/misc ']'
+ dnsmasq --conf-file=/dev/null -u nobody --strict-order --bind-interfaces --pid-file=/run/waydroid-lxc/dnsmasq.pid --listen-address 192.168.240.1 --dhcp-range 192.168.240.2,192.168.240.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --interface=waydroid0 --dhcp-leasefile=/var/lib/misc/dnsmasq.waydroid0.leases --dhcp-authoritative
+ cleanup
+ set +e
+ '[' 1 = 1 ']'
+ echo 'Failed to setup waydroid-net.'
Failed to setup waydroid-net.
+ stop force
+ '[' xtrue = xtrue ']'
+ '[' -f /run/waydroid-lxc/network_up ']'
+ '[' force = force ']'
+ '[' -d /sys/class/net/waydroid0 ']'
+ _ifdown
+ ip addr flush dev waydroid0
+ ip link set dev waydroid0 down
+ use_nft
+ '[' -n /usr/bin/nft ']'
+ nft list ruleset
+ '[' true = true ']'
+ stop_nftables
+ NFT_RULESET='add table inet lxc;
delete table inet lxc;
add table ip lxc;
delete table ip lxc;
'
+ '[' false = true ']'
+ nft 'add table inet lxc;
delete table inet lxc;
add table ip lxc;
delete table ip lxc;
'
++ cat /run/waydroid-lxc/dnsmasq.pid
+ pid=
+ rm -f /run/waydroid-lxc/dnsmasq.pid
+ ls '/sys/class/net/waydroid0/brif/*'
+ ip link delete waydroid0
+ rm -f /run/waydroid-lxc/network_up
+ exit 1
+ cleanup
+ set +e
+ '[' 1 = 1 ']'
+ echo 'Failed to setup waydroid-net.'
Failed to setup waydroid-net.
+ stop force
+ '[' xtrue = xtrue ']'
+ '[' -f /run/waydroid-lxc/network_up ']'
+ '[' force = force ']'
+ '[' -d /sys/class/net/waydroid0 ']'
+ rm -f /run/waydroid-lxc/network_up
+ exit 1
```
It won't start even with the local dnsmasq stopped.

**Comment by pupstime5** [comment]
`(029138) [11:58:12] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
RTNETLINK answers: Operation not permitted
Failed to setup waydroid-net.
(029138) [11:58:12] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(029138) [11:58:12] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(029258) [11:58:12] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(029258) [11:58:12] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(029271) [11:58:18] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(029271) [11:58:18] *** output passed to waydroid stdout, not to this log ***
(029275) [12:04:24] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(029275) [12:04:24] *** output passed to waydroid stdout, not to this log ***
`
for context, I run this on ubuntu 22.04 proot distro in userland arm64, waydroid version 1.4.3, can anyone help me with this error?

**Comment by silverhadch** [comment]
For me it occured because devilbox was running on Port 53.

**Comment by nos1609** [comment]
`sudo modprobe bridge` works on  6.6.87.2-microsoft-standard-WSL2
